name: Load Matrix from File

on:
  workflow_call:
    inputs:
      filename:
        type: string
        required: false
        default: ./.github/matrix.json
    outputs:
      matrix:
        value: ${{ jobs.load-matrix.outputs.matrix }}
      variant_count:
        value: ${{ jobs.load-matrix.outputs.variant_count }}

jobs:
  load-matrix:
    name: Load Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
      variant_count: ${{ steps.count-variants.outputs.variant_count }}
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: load-matrix
        run: echo "matrix=$(cat ${{ inputs.filename }} | jq -ca)" >> $GITHUB_OUTPUT

      - id: count-variants
        run: echo "variant_count=$(cat ${{ inputs.filename }} | jq -r '.include | length')" >> $GITHUB_OUTPUT
