# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      build_command:
        required: true
        type: string
      app_name:
        required: true
        type: string

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    container: 
      image: node:${{ inputs.node_version }}
      options: --user 1001:121
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Cache npm deps
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build ${{ inputs.app_name }}
        run: npm run ${{ inputs.build_command }}
